SELECT CLIENTE.NOME, PEDIDO.IDPEDIDO, PEDIDO.DATAPEDIDO, PEDIDO.VALORTOTALPEDIDO
FROM CLIENTE JOIN PEDIDO ON CLIENTE.IDCLIENTE = PEDIDO.CLIENTE_IDCLIENTE
WHERE CLIENTE.TIPOCLIENTE_IDTIPOCLIENTE = 1 AND PEDIDO.VALORTOTALPEDIDO = 0;
